# Generated by Django 5.0 on 2023-12-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("glancenote", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"verbose_name_plural": "Classes"},
        ),
        migrations.AlterModelOptions(
            name="studentclass",
            options={"verbose_name_plural": "StudentClasses"},
        ),
    ]
