# Generated by Django 5.0 on 2023-12-15 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glancenote", "0003_assistant_course_enrollment_institution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="due_date",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="assignmentcompletion",
            name="completion_date",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="assignmentcompletion",
            name="grade",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taught_courses",
                to="glancenote.teacherprofile",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="institution",
            name="domains",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="institution",
            name="website",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="log",
            name="professor_notes",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="log",
            name="student_notes",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="courses_taught",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="email_verified",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="phone_verified",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="registration_tokens",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
