# Generated by Django 5.0 on 2023-12-15 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("glancenote", "0004_alter_assignment_due_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacherprofile",
            name="courses_taught",
        ),
    ]
