# Generated by Django 5.0 on 2023-12-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glancenote", "0005_remove_teacherprofile_courses_taught"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
