# Generated by Django 5.0 on 2023-12-15 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("glancenote", "0006_course_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={"verbose_name_plural": "Enrollments"},
        ),
    ]
