# Generated by Django 5.0 on 2023-12-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glancenote", "0007_alter_enrollment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="enrollment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
