# Generated by Django 5.0 on 2023-12-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glancenote", "0008_enrollment_enrollment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="unique_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
