# Generated by Django 5.0 on 2023-12-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glancenote", "0009_student_unique_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignmentcompletion",
            name="name",
        ),
        migrations.AddField(
            model_name="assignmentcompletion",
            name="assignment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="glancenote.assignment",
            ),
        ),
    ]
