# Generated by Django 5.0 on 2023-12-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glancenote", "0011_assistant_assistant_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_id", models.CharField(max_length=255)),
                ("file_name", models.CharField(max_length=255)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="assistant",
            name="files",
        ),
        migrations.AddField(
            model_name="assistant",
            name="files",
            field=models.ManyToManyField(to="glancenote.uploadedfile"),
        ),
    ]
