# Generated by Django 5.0 on 2023-12-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glancenote", "0013_lecture"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentprofile",
            name="thread_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
