# Generated by Django 5.0 on 2023-12-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glancenote", "0014_parentprofile_thread_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="institutions", to="glancenote.course"
            ),
        ),
    ]
